const leadershipSections = [
  {
    id: 'pastors',
    title: 'Reverend Pastors',
    overline: 'The pastoral ministry',
    description: 'Our two reverend pastors guide the congregation through preaching, prayer, and pastoral care.',
    countLabel: '2 pastors',
    icon: 'church',
    gridClass: 'sm:grid-cols-2',
    members: [{
        id: 'parish-pastor',
        role: 'Parish Pastor',
        name: 'Rev. Dr. Mokoko Mbue Thomas',
        picture: '/mokoko-thomas.jpg',
      },
      {
        id: 'associate-pastor',
        role: 'Associate Pastor',
        name: 'Rev. Saihnom Read Fomufod',
        picture: '/saihnom-read.png',
      }
    ]
    
  },
  //I need 25 elders and 12 presidents
  {
    id: 'elders',
    title: 'Kirk Session Elders',
    overline: 'Serving the congregation',
    description: 'Around 24 elders support the spiritual life, care, and fellowship of our Congregation.',
    countLabel: 'About 24 elders',
    icon: 'shield_person',
    gridClass: 'sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4',
    members: [{
        id: 'elder-1',
        role: 'Elder 01',
        name: 'Name to be announced',
        picture: '/elders/elder-1.jpg',
      },
      {
        id: 'elder-2',
        role: 'Elder 02',
        name: 'Name to be announced',
        picture: '/elders/elder-2.jpg',
      },
        {
            id: 'elder-3',  
            role: 'Elder 03',
            name: 'Name to be announced',
            picture: '/elders/elder-3.jpg',
        },
        {
            id: 'elder-4',
            role: 'Elder 04',
            name: 'Name to be announced',
            picture: '/elders/elder-4.jpg',
        },
        {
            id: 'elder-5',
            role: 'Elder 05',
            name: 'Name to be announced',
            picture: '/elders/elder-5.jpg',
        },
        {
            id: 'elder-6',
            role: 'Elder 06',
            name: 'Name to be announced',
            picture: '/elders/elder-6.jpg',
        },
        {
            id: 'elder-7',
            role: 'Elder 07',
            name: 'Name to be announced',
            picture: '/elders/elder-7.jpg',
        },
        {
            id: 'elder-8',
            role: 'Elder 08',
            name: 'Name to be announced',
            picture: '/elders/elder-8.jpg',
        },
        {
            id: 'elder-9',
            role: 'Elder 09',
            name: 'Name to be announced',
            picture: '/elders/elder-9.jpg',
        },
        {
            id: 'elder-10',
            role: 'Elder 10',
            name: 'Name to be announced',
            picture: '/elders/elder-10.jpg',
        },
        {
            id: 'elder-11',
            role: 'Elder 11',
            name: 'Name to be announced',
            picture: '/elders/elder-11.jpg',
        },
        {
            id: 'elder-12',
            role: 'Elder 12',
            name: 'Name to be announced',
            picture: '/elders/elder-12.jpg',
        },
        {
            id: 'elder-13',
            role: 'Elder 13',
            name: 'Name to be announced',
            picture: '/elders/elder-13.jpg',
        },
        {
            id: 'elder-14',
            role: 'Elder 14',
            name: 'Name to be announced',
            picture: '/elders/elder-14.jpg',
        },
        {
            id: 'elder-15',
            role: 'Elder 15',
            name: 'Name to be announced',
            picture: '/elders/elder-15.jpg',
        },
        {
            id: 'elder-16',
            role: 'Elder 16',
            name: 'Name to be announced',
            picture: '/elders/elder-16.jpg',
        },
        {
            id: 'elder-17',
            role: 'Elder 17',
            name: 'Name to be announced',
            picture: '/elders/elder-17.jpg',
        },
        {
            id: 'elder-18',
            role: 'Elder 18',
            name: 'Name to be announced',
            picture: '/elders/elder-18.jpg',
        },
        {
            id: 'elder-19',
            role: 'Elder 19',
            name: 'Name to be announced',
            picture: '/elders/elder-19.jpg',
        },
        {
            id: 'elder-20',
            role: 'Elder 20',
            name: 'Name to be announced',
            picture: '/elders/elder-20.jpg',
        },
        {
            id: 'elder-21',
            role: 'Elder 21',
            name: 'Name to be announced',
            picture: '/elders/elder-21.jpg',
        },
        {
            id: 'elder-22',
            role: 'Elder 22',
            name: 'Name to be announced',
            picture: '/elders/elder-22.jpg',
        },
        {
            id: 'elder-23',
            role: 'Elder 23',
            name: 'Name to be announced',
            picture: '/elders/elder-23.jpg',
        },
        {
            id: 'elder-24',
            role: 'Elder 24',
            name: 'Name to be announced',
            picture: '/elders/elder-24.jpg',
        },
        {
            id: 'elder-25',
            role: 'Elder 25',
            name: 'Name to be announced',
            picture: '/elders/elder-25.jpg',
        },
    ]
  },
  {
    id: 'presidents',
    title: 'Group & Choir Leaders',
    overline: 'Fellowship and worship',
    description: 'Twelve group leaders guide our church groups and choirs in fellowship, worship, and service.',
    icon: 'groups',
    gridClass: 'sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4',
    members: [
      {
        id: 'president-1',
        role: 'Group Leader 01',
        name: 'Name to be announced',
        picture: '/presidents/president-1.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-2',
        role: 'Group Leader 02',
        name: 'Name to be announced',
        picture: '/presidents/president-2.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-3',
        role: 'Group Leader 03',
        name: 'Name to be announced',
        picture: '/presidents/president-3.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-4',
        role: 'Group Leader 04',
        name: 'Name to be announced',
        picture: '/presidents/president-4.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-5',
        role: 'Group Leader 05',
        name: 'Name to be announced',
        picture: '/presidents/president-5.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-6',
        role: 'Group Leader 06',
        name: 'Name to be announced',
        picture: '/presidents/president-6.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-7',
        role: 'Group Leader 07',
        name: 'Name to be announced',
        picture: '/presidents/president-7.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-8',
        role: 'Group Leader 08',
        name: 'Name to be announced',
        picture: '/presidents/president-8.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-9',
        role: 'Group Leader 09',
        name: 'Name to be announced',
        picture: '/presidents/president-9.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-10',
        role: 'Group Leader 10',
        name: 'Name to be announced',
        picture: '/presidents/president-10.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-11',
        role: 'Group Leader 11',
        name: 'Name to be announced',
        picture: '/presidents/president-11.jpg',
        group: 'Group / choir to be announced',
      },
      {
        id: 'president-12',
        role: 'Group Leader 12',
        name: 'Name to be announced',
        picture: '/presidents/president-12.jpg',
        group: 'Group / choir to be announced',
      },
    ],
        countLabel: '12 group leaders'
  },
];

export default leadershipSections;
