const leadershipSections = [
  {
    id: 'pastors',
    title: 'Reverend Pastors',
    overline: 'The pastoral ministry',
    description: 'Our two reverend pastors guide the congregation through preaching, prayer, and pastoral care.',
    countLabel: '2 pastors',
    icon: 'church',
    gridClass: 'sm:grid-cols-2',
    members: [{
        id: 'parish-pastor',
        role: 'Parish Pastor',
        name: 'Rev. Dr. Mokoko Mbue Thomas',
        picture: '/mokoko-thomas.jpg',
      },
      {
        id: 'associate-pastor',
        role: 'Associate Pastor',
        name: 'Rev. Saihnom Read Fomufod',
        picture: '/saihnom-read.png',
      }
    ]
    
  },
  //I need 25 elders and 12 presidents
  {
    id: 'elders',
    title: 'Kirk Session Elders',
    overline: 'Serving the congregation',
    description: '25 elders support the spiritual life, care, and fellowship of our Congregation.',
    countLabel: '25 elders',
    icon: 'shield_person',
    gridClass: 'sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4',
    members: [
    {
        id: 'elder-1',
        role: 'ChairPerson',
        name: 'Elder Enow Evelyn',
        picture: '/elders/elder-25.jpg',
    },
    {
        id: 'elder-2',
        role: 'V. Chairperson',
        name: 'Elder Mesape Epie Emmanuel',
        picture: '/elders/elder-24.jpg',
    },
    {
        id: 'elder-3',
        role: 'Secretary & Women of the Cong. Elder',
        name: 'Elder Dibo Princewill',
        picture: '/elders/elder-15.jpg',
    },
    {
        id: 'elder-4',
        role: 'CWF Elder',
        name: 'Elder Enow Celine',
        picture: '/elders/elder-1.jpg',
    },
    {
        id: 'elder-5',
        role: 'CWF Elder',
        name: 'Elder Mokoro Comfort',
        picture: '/elders/elder-2.jpg',
    },
    {
        id: 'elder-6',
        role: 'CMF & Project C. Elder',
        name: 'Elder Ako Ako Thomas',
        picture: '/elders/elder-3.jpg',
    },
    {
        id: 'elder-7',
        role: 'CMF Elder',
        name: 'Elder Ngwane Peter',
        picture: '/elders/elder-4.jpg',
    },
    {
        id: 'elder-8',
        role: 'CYF/Youth of the Cong. & Doctrine Classes Elder',
        name: 'Elder Ojong Dorothy Nsonya',
        picture: '/ojong-dorothy.jpeg',
    },
    {
        id: 'elder-9',
        role: 'Redemption Chior Elder',
        name: 'Elder Ekole Chabanga',
        picture: '/elders/elder-6.jpg',
    },
    {
        id: 'elder-10',
        role: 'Redemption Chior Elder',
        name: 'Elder Ayuk Jacobine',
        picture: '/ayuk-jacobine.jpg',
    },
    {
        id: 'elder-11',
        role: 'Temple Choir Elder',
        name: 'Elder Asanji Godfred',
        picture: '/elders/elder-8.jpg',
    },
    {
        id: 'elder-12',
        role: 'Hallelujah Choir Elder',
        name: 'Elder Ndip Mbi Shadrack',
        picture: '/elders/elder-9.jpg',
    },
    {
        id: 'elder-13',
        role: 'Betesedi Ba Loba Chior Elder',
        name: 'Elder Fonjong Helen',
        picture: '/elders/elder-10.jpg',
    },
    {
        id: 'elder-14',
        role: 'Bapresca Choir Elder',
        name: 'Elder Bolabo Hadison Longe',
        picture: '/elders/elder-11.jpg',
    },
    {
        id: 'elder-15',
        role: 'Ndola Christo Elder',
        name: 'Elder Alobwede Dorine Emade',
        picture: '/alobwede-dorine.jpg',
    },
    {
        id: 'elder-16',
        role: 'Men of the Congregation & Parish Car Elder',
        name: 'Elder Ndi Mathias',
        picture: '/ndi-mathias.jpg',
    },
    {
        id: 'elder-17',
        role: 'Men of the Congregation & Doctrine Classes Elder',
        name: 'Elder Mesumbe Olive',
        picture: '/elders/elder-14.jpg',
    },
    {
        id: 'elder-18',
        role: 'Women of the Cong. & Social Welfare C. Elder',
        name: 'Elder Atem Samuel Mbi',
        picture: '/elders/elder-15.jpg',
    },
    {
        id: 'elder-19',
        role: 'Praise & Worship Team Elder',
        name: 'Elder Ku Edmond Ofon',
        picture: '/elders/elder-16.jpg',
    },
    {
        id: 'elder-20',
        role: 'Vestry & Session Socials Elder',
        name: 'Elder Edith Fri Njoh',
        picture: '/fri-njoh.jpg',
    },
    {
        id: 'elder-21',
        role: 'Sanctuary & Decoration C. Elder',
        name: 'Elder Sume Munge Jill',
        picture: '/elders/elder-18.jpg',
    },
    {
        id: 'elder-22',
        role: 'Hostel Elder',
        name: 'Elder Egbe Mbu Anthony',
        picture: '/elders/elder-19.jpg',
    },
    {
        id: 'elder-23',
        role: 'YP & Sunday School Elder',
        name: 'Elder Arrey Lionel Ayuk',
        picture: '/arrey-lionel.jpg',
    },
    {
        id: 'elder-24',
        role: 'Health Commitee Elder',
        name: 'Elder Eyong Mary Tabenyang',
        picture: '/elders/elder-21.jpg',
    },
    {
        id: 'elder-25',
        role: 'Elder 22',
        name: 'Name to be announced',
        picture: '/elders/elder-22.jpg',
    },
]
  },
  {
    id: 'presidents',
    title: 'Group & Choir Leaders',
    overline: 'Fellowship and worship',
    description: 'Twelve group leaders guide our church groups and choirs in fellowship, worship, and service.',
    icon: 'groups',
    gridClass: 'sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4',
    members: [
      {
        id: 'president-1',
        role: 'President',
        name: 'Mr. Musoh Isaiah Anim',
        picture: '/presidents/president-1.jpg',
        group: 'Christian Men Fellowship (CMF)',
      },
      {
        id: 'president-2',
        role: 'President',
        name: 'Name to be announced',
        picture: '/presidents/president-2.jpg',
        group: 'Christian Women Fellowship (CWF)',
      },
      {
        id: 'president-3',
        role: 'President',
        name: 'Sis. Obase Marie',
        picture: '/obase-marie.png',
        group: 'Christian Youth Fellowship (CYF)',
      },
      {
        id: 'president-4',
        role: 'President',
        name: 'Mrs. Ijang Christy',
        picture: '/ijang-christy.jpg',
        group: 'Redemption Choir',
      },
      {
        id: 'president-5',
        role: 'President',
        name: 'Mrs. Bisong Beatrice',
        picture: '/bisong-beatrice.jpg',
        group: 'Temple Choir',
      },
      {
        id: 'president-6',
        role: 'President',
        name: 'Mr. Ntali Michael',
        picture: '/ntali-michael.jpg',
        group: 'Hallelujah Choir',
      },
      {
        id: 'president-7',
        role: 'President',
        name: 'Mr. Epoge Daniel',
        picture: '/epoge-daniel.jpg',
        group: 'Bapresca Choir',
      },
      {
        id: 'president-8',
        role: 'President',
        name: 'Name to be announced',
        picture: '/presidents/president-8.jpg',
        group: 'Ndola Christo Choir',
      },
      {
        id: 'president-9',
        role: 'President',
        name: 'Name to be announced',
        picture: '/presidents/president-9.jpg',
        group: 'Betesedi Ba Loba Choir',
      },
      {
        id: 'president-10',
        role: 'President',
        name: 'Name to be announced',
        picture: '/presidents/president-10.jpg',
        group: 'Praise & Worship Team',
      },
      
    ],
        countLabel: '10 group leaders'
  },
];

export default leadershipSections;
